# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-XBEL
version:      1.3
version_from: lib/Apache/XBEL.pm
installdirs:  site
requires:
    Apache:                        1.26
    Cwd:                           0
    Digest::MD5:                   1.0
    File::Basename:                0
    File::Copy:                    0
    File::Spec:                    0
    Memoize:                       0
    XML::LibXML:                   1.51
    XML::LibXSLT:                  1.31

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
